version: "3"

services:
    flask:
        container_name: flask
        build:          # Create image from Dockerfile
            context: ./flask    # Dockerfile location
            dockerfile: Dockerfile-flask  # Dockerfile name
        volumes:
            - ./flask:/usr/src/app  # Update app.py on every start
        networks:
            - db_nw     # Connect flask with database
            - web_nw    # Connect flask with nginx
            
    nginx:
        image: nginx    # Create from Docker Hub
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf    # Hostfolder:Containerfolder
        ports:
            - 5000:80   # Hostport:Containerport
        depends_on:
            - flask
        networks:
            - web_nw    # Connect flask with nginx
    db:
        container_name: db 
        build:          # Create from Dockerfile
            context: ./postgres # Dockerfile location
            dockerfile: Dockerfile-psql  # Dockerfile name
        volumes:
            - db_data1:/var/lib/postgresql/data
        ports:
            - 5432:5432 
        networks:
            - db_nw     # Connect flask with database
            
networks:
    db_nw:
        driver: bridge
    web_nw:
        driver: bridge
        
volumes:
    db_data1: